In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [8]:
data = pd.read_csv("pre-processed-data.csv")
data

,gwb_code_10,a_inw,a_man,a_vrouw,a_00_14,a_15_24,a_25_44,a_45_64,a_65_oo,a_ongeh,...,g_afs_kv,g_afs_sc,g_3km_sc,a_opp_ha,a_lan_ha,a_wat_ha,ste_mvs,ste_oad,sporting,loneliness
0,GM0003,11721,5720,6001,1718,1238,2376,3491,2898,4981,...,"0,9","0,9","6,4",2458,2378,80,3,1067,36.3,49.4
1,WK000300,11720,5720,6000,1715,1235,2375,3490,2895,4980,...,"0,9","0,9","6,4",2458,2378,80,3,1067,36.3,49.4
2,BU00030000,2370,1135,1230,230,225,500,715,700,985,...,"1,2","1,1","7,1",90,84,5,3,1210,35.4,51.6
3,BU00030001,3035,1505,1530,480,350,570,990,640,1285,...,"1,0","1,0","4,0",163,158,5,4,903,41.5,41.5
4,BU00030002,5725,2760,2960,900,580,1205,1560,1480,2415,...,"0,7","0,7","7,7",295,284,11,3,1140,33.0,54.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17108,WK197820,715,360,355,125,110,120,205,160,275,...,"0,8","0,7","1,0",638,631,7,5,64,38.7,37.7
17109,BU19782001,10,5,5,5,5,0,5,0,5,...,"2,5","2,9","0,7",580,574,6,5,18,NaN,NaN
17110,BU19782002,440,225,215,60,70,80,135,95,160,...,"0,5","0,2","1,0",11,11,0,5,75,40.2,38.9
17111,BU19782003,150,70,80,40,20,20,40,35,60,...,"1,2","1,7","1,0",28,28,0,5,36,34.2,34.8
17112,BU19782004,115,60,60,25,15,20,35,30,40,...,"1,4","0,9","1,0",20,19,1,5,59,38.6,36.6

g_afs_hp      3.939
g_afs_gs      3.939
g_afs_kv      3.939
ste_oad       0.012
sporting      5.762
loneliness    5.762
dtype: float64